/* Generated by Phoenix Tuner X */
package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import com.ctre.phoenix6.BaseStatusSignal;
import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.StatusCode;
import com.ctre.phoenix6.StatusSignal;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.controls.DutyCycleOut;
import com.ctre.phoenix6.controls.Follower;
import com.ctre.phoenix6.controls.MotionMagicVoltage;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.signals.ForwardLimitSourceValue;
import com.ctre.phoenix6.signals.ForwardLimitTypeValue;
import com.ctre.phoenix6.signals.GravityTypeValue;
import com.ctre.phoenix6.signals.MotorAlignmentValue;
import com.ctre.phoenix6.signals.NeutralModeValue;
import com.ctre.phoenix6.signals.ReverseLimitSourceValue;
import com.ctre.phoenix6.signals.ReverseLimitTypeValue;
import com.ctre.phoenix6.sim.ChassisReference;
import com.ctre.phoenix6.sim.TalonFXSimState;
import edu.wpi.first.epilogue.Logged;
import edu.wpi.first.math.system.plant.DCMotor;
import edu.wpi.first.units.measure.*;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.simulation.ElevatorSim;
import edu.wpi.first.wpilibj.smartdashboard.Mechanism2d;
import edu.wpi.first.wpilibj.smartdashboard.MechanismLigament2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import edu.wpi.first.wpilibj2.command.button.Trigger;
import java.util.function.DoubleSupplier;
import java.util.function.Supplier;

public class Climber extends SubsystemBase {
  /** Position setpoints for the climber. */
  public enum Setpoint {
    Bottom(Rotations.of(0)),
    Middle(Inches.of(3.5)),
    Top(Inches.of(7.5)); // 16.5 rotations

    /** The position target of the setpoint in angular units. */
    public final Angle target;

    /** The position target of the setpoint in linear units. */
    public final Distance targetDist;

    private Setpoint(Angle target) {
      this.target = target;
      this.targetDist = kDrumRadius.times(target.in(Radians));
    }

    private Setpoint(Distance target) {
      this.target = Radians.of(target.div(kDrumRadius).magnitude());
      this.targetDist = target;
    }
  }

  private static final int kNumConfigAttempts = 2;

  private static final double kGearRatio = 24.6;
  private static final Distance kDrumRadius = Meters.of(0.009525);
  private static final Distance kMaxHeight = Meters.of(0);

  /* leader and follower motors */
  private final CANBus kCANBus = new CANBus("Default Name");
  private final TalonFX motor_id_19 = new TalonFX(19, kCANBus); // follower
  private final TalonFX motor_id_15 = new TalonFX(15, kCANBus); // leader

  /* device status signals */
  private final StatusSignal<Angle> motor_id_15Position = motor_id_15.getPosition(false);
  private final StatusSignal<AngularVelocity> motor_id_15Velocity = motor_id_15.getVelocity(false);
  private final StatusSignal<Current> motor_id_15TorqueCurrent =
      motor_id_15.getTorqueCurrent(false);
  private final StatusSignal<Temperature> motor_id_15Temperature = motor_id_15.getDeviceTemp(false);
  private final StatusSignal<Current> motor_id_19TorqueCurrent =
      motor_id_19.getTorqueCurrent(false);
  private final StatusSignal<Temperature> motor_id_19Temperature = motor_id_19.getDeviceTemp(false);

  /* controls used by the leader motors */
  private final MotionMagicVoltage setpointRequest = new MotionMagicVoltage(0);
  private final DutyCycleOut manualRequest = new DutyCycleOut(0);
  private final DutyCycleOut calibrationRequest =
      new DutyCycleOut(-0.1).withIgnoreHardwareLimits(true).withIgnoreSoftwareLimits(true);

  /** Trigger to detect when the climber drives into a hard stop. */
  public final Trigger isHardStop =
      new Trigger(
              () -> {
                return motor_id_15Velocity.getValue().abs(RotationsPerSecond) < 1
                    && motor_id_15TorqueCurrent.getValue().abs(Amps) > 10;
              })
          .debounce(0.1);

  /* simulation */
  private final ElevatorSim climberSim_motor_id_15 =
      new ElevatorSim(
          DCMotor.getKrakenX60Foc(2),
          kGearRatio,
          5,
          kDrumRadius.in(Meters),
          0.0,
          kMaxHeight.in(Meters),
          true,
          0.0);

  private static final double kSimLoopPeriod = 0.002; // 2 ms
  private Notifier simNotifier = null;
  private double lastSimTime = 0.0;

  /* Mechanism2d visualization of the climber */
  private final Mechanism2d mech2d = new Mechanism2d(1, kMaxHeight.in(Meters));
  private final MechanismLigament2d motor_id_15Mech2d =
      mech2d
          .getRoot("motor_id_15 Root", 0.500, 0)
          .append(
              new MechanismLigament2d(
                  "motor_id_15", climberSim_motor_id_15.getPositionMeters(), 90));

  /** Configs common across all motors. */
  private static final TalonFXConfiguration motorInitialConfigs = new TalonFXConfiguration();

  /** Configs common across just the leader motors. */
  private static final TalonFXConfiguration leaderInitialConfigs = motorInitialConfigs.clone();

  /** Configs for {@link #motor_id_19}. */
  private final TalonFXConfiguration motor_id_19Configs =
      motorInitialConfigs
          .clone()
          .withMotorOutput(
              motorInitialConfigs.MotorOutput.clone().withNeutralMode(NeutralModeValue.Brake))
          .withCurrentLimits(
              motorInitialConfigs
                  .CurrentLimits
                  .clone()
                  .withStatorCurrentLimit(Amps.of(120))
                  .withStatorCurrentLimitEnable(true))
          .withSlot0(
              motorInitialConfigs
                  .Slot0
                  .clone()
                  .withKP(98.4)
                  .withKI(0)
                  .withKD(0)
                  .withKS(0.2)
                  .withKV(2.952)
                  .withKA(0)
                  .withKG(0)
                  .withGravityType(GravityTypeValue.Elevator_Static))
          .withFeedback(motorInitialConfigs.Feedback.clone().withSensorToMechanismRatio(24.6))
          .withHardwareLimitSwitch(
              motorInitialConfigs
                  .HardwareLimitSwitch
                  .clone()
                  .withForwardLimitEnable(true)
                  .withForwardLimitAutosetPositionEnable(false)
                  .withForwardLimitRemoteSensorID(0)
                  .withForwardLimitSource(ForwardLimitSourceValue.LimitSwitchPin)
                  .withForwardLimitType(ForwardLimitTypeValue.NormallyOpen)
                  .withReverseLimitAutosetPositionEnable(false)
                  .withReverseLimitEnable(true)
                  .withReverseLimitRemoteSensorID(0)
                  .withReverseLimitSource(ReverseLimitSourceValue.LimitSwitchPin)
                  .withReverseLimitType(ReverseLimitTypeValue.NormallyOpen))
          .withMotionMagic(
              motorInitialConfigs
                  .MotionMagic
                  .clone()
                  .withMotionMagicCruiseVelocity(RotationsPerSecond.of(3.252032520325203))
                  .withMotionMagicAcceleration(RotationsPerSecondPerSecond.of(16.260162601626014)));

  /** Configs for {@link #motor_id_15}. */
  private final TalonFXConfiguration motor_id_15Configs =
      leaderInitialConfigs
          .clone()
          .withMotorOutput(
              leaderInitialConfigs.MotorOutput.clone().withNeutralMode(NeutralModeValue.Brake))
          .withCurrentLimits(
              leaderInitialConfigs
                  .CurrentLimits
                  .clone()
                  .withStatorCurrentLimit(Amps.of(120))
                  .withStatorCurrentLimitEnable(true))
          .withSlot0(
              leaderInitialConfigs
                  .Slot0
                  .clone()
                  .withKP(98.4)
                  .withKI(0)
                  .withKD(0)
                  .withKS(0.2)
                  .withKV(2.952)
                  .withKA(0)
                  .withKG(0)
                  .withGravityType(GravityTypeValue.Elevator_Static))
          .withFeedback(leaderInitialConfigs.Feedback.clone().withSensorToMechanismRatio(24.6))
          .withHardwareLimitSwitch(
              leaderInitialConfigs
                  .HardwareLimitSwitch
                  .clone()
                  .withForwardLimitEnable(true)
                  .withForwardLimitAutosetPositionEnable(false)
                  .withForwardLimitRemoteSensorID(0)
                  .withForwardLimitSource(ForwardLimitSourceValue.LimitSwitchPin)
                  .withForwardLimitType(ForwardLimitTypeValue.NormallyOpen)
                  .withReverseLimitAutosetPositionEnable(false)
                  .withReverseLimitEnable(true)
                  .withReverseLimitRemoteSensorID(0)
                  .withReverseLimitSource(ReverseLimitSourceValue.LimitSwitchPin)
                  .withReverseLimitType(ReverseLimitTypeValue.NormallyOpen))
          .withMotionMagic(
              leaderInitialConfigs
                  .MotionMagic
                  .clone()
                  .withMotionMagicCruiseVelocity(RotationsPerSecond.of(3.252032520325203))
                  .withMotionMagicAcceleration(RotationsPerSecondPerSecond.of(16.260162601626014)));

  public Climber() {
    super("Climber");
    StatusCode status = motor_id_19.getConfigurator().apply(motor_id_19Configs);

    for (int i = 0; i < kNumConfigAttempts; ++i) {
      if (status.isOK()) break;
      status = motor_id_19.getConfigurator().apply(motor_id_19Configs);
    }
    if (!status.isOK()) {
      System.out.println("ERROR Configuring Climber follower motor: " + status);
    }

    status = motor_id_15.getConfigurator().apply(motor_id_15Configs);
    for (int i = 0; i < kNumConfigAttempts; ++i) {
      if (status.isOK()) break;
      status = motor_id_15.getConfigurator().apply(motor_id_15Configs);
    }
    if (!status.isOK()) {
      System.out.println("ERROR Configuring Climber leader motor: " + status);
    }

    motor_id_19.setControl(new Follower(motor_id_15.getDeviceID(), MotorAlignmentValue.Aligned));

    if (Utils.isSimulation()) {
      SmartDashboard.putData("climber", mech2d);
      startSimThread();
    }

    optimizeCAN();
    System.out.println("Climber Subsystem Initialized");
  }

  private void optimizeCAN() {
    motor_id_15.getPosition().setUpdateFrequency(100);
    motor_id_15.getVelocity().setUpdateFrequency(100);
    motor_id_15.getSupplyCurrent().setUpdateFrequency(50);
    motor_id_15.getDeviceTemp().setUpdateFrequency(4);

    motor_id_15.optimizeBusUtilization();

    motor_id_19.getSupplyCurrent().setUpdateFrequency(10);
    motor_id_19.getDeviceTemp().setUpdateFrequency(4);

    motor_id_19.optimizeBusUtilization();
  }

  /**
   * @return The Position of the climber
   */
  @Logged
  public Angle getPosition() {
    return motor_id_15Position.getValue();
  }

  @Logged
  public Distance getPositionDistance() {
    return kDrumRadius.times(motor_id_15Position.getValue().in(Radians));
  }

  @Logged
  public double getPositionInches() {
    return kDrumRadius.times(motor_id_15Position.getValue().in(Radians)).in(Inches);
  }

  /**
   * @return The Velocity of the climber
   */
  @Logged
  public AngularVelocity getVelocity() {
    return motor_id_15Velocity.getValue();
  }

  /**
   * @return The TorqueCurrent of the climber
   */
  @Logged
  public Current getTorqueCurrentA() {
    return motor_id_15TorqueCurrent.getValue();
  }

  /**
   * @return The TorqueCurrent of the climber
   */
  @Logged
  public Current getTorqueCurrentB() {
    return motor_id_19TorqueCurrent.getValue();
  }

  /**
   * @return The Temperature of the climber
   */
  @Logged
  public double getTempuratureAFahrenheit() {
    return motor_id_15Temperature.getValue().in(Fahrenheit);
  }

  /**
   * @return The Temperature of the climber
   */
  @Logged
  public double getTempuratureBAFahrenheit() {
    return motor_id_19Temperature.getValue().in(Fahrenheit);
  }

  /**
   * Holds the climber at the current position using PID.
   *
   * @return Command to run
   */
  public Command holdPosition() {
    return runOnce(() -> setpointRequest.withPosition(motor_id_15Position.getValue()))
        .andThen(
            run(
                () -> {
                  motor_id_15.setControl(setpointRequest);
                }));
  }

  /**
   * Drives the climber to the provided position setpoint.
   *
   * @param setpoint Function returning the setpoint to apply
   * @return Command to run
   */
  public Command goToSetpoint(Supplier<Setpoint> setpoint) {
    return run(
        () -> {
          setpointRequest.withPosition(setpoint.get().target);
          motor_id_15.setControl(setpointRequest);
        });
  }

  /**
   * Manually drives the climber with the provided duty cycle output.
   *
   * @param manualOutput Function returning the duty cycle to apply
   * @return Command to run
   */
  public Command manualDrive(DoubleSupplier manualOutput) {
    return run(
        () -> {
          manualRequest.withOutput(manualOutput.getAsDouble());
          motor_id_15.setControl(manualRequest);
        });
  }

  /**
   * Recalibrates the climber zero point. This slowly drives the climber down until we see a drop in
   * velocity and a spike in stator current, indicating that we've hit a hard stop.
   *
   * @return Command to run
   */
  public Command calibrateZero() {
    return run(() -> {
          motor_id_15.setControl(calibrationRequest);
        })
        .until(isHardStop)
        .andThen(
            manualDrive(() -> 0.0)
                .withTimeout(0.25)
                .finallyDo(
                    () -> {
                      motor_id_19.setPosition(Rotations.of(0));
                      motor_id_15.setPosition(Rotations.of(0));
                    }));
  }

  @Override
  public void periodic() {
    /* refresh all status signals */
    BaseStatusSignal.refreshAll(
        motor_id_15Position,
        motor_id_15Velocity,
        motor_id_15TorqueCurrent,
        motor_id_15Temperature,
        motor_id_19TorqueCurrent,
        motor_id_19Temperature);

    // motor_id_15Mech2d.setLength(
    //    motor_id_15Position.getValueAsDouble() * kDrumRadius.in(Meters) * 2 * Math.PI);
  }

  private void startSimThread() {
    motor_id_19.getSimState().Orientation = ChassisReference.CounterClockwise_Positive;
    motor_id_19.getSimState().setMotorType(TalonFXSimState.MotorType.KrakenX60);
    motor_id_15.getSimState().Orientation = ChassisReference.CounterClockwise_Positive;
    motor_id_15.getSimState().setMotorType(TalonFXSimState.MotorType.KrakenX60);

    lastSimTime = Utils.getCurrentTimeSeconds();

    /* Run simulation at a faster rate so PID gains behave more reasonably */
    simNotifier =
        new Notifier(
            () -> {
              /* Calculate the time delta */
              final double currentTime = Utils.getCurrentTimeSeconds();
              final double deltaTime = currentTime - lastSimTime;
              lastSimTime = currentTime;

              final var motor_id_19Sim = motor_id_19.getSimState();
              final var motor_id_15Sim = motor_id_15.getSimState();

              /* First set the supply voltage of all the devices */
              motor_id_19Sim.setSupplyVoltage(RobotController.getBatteryVoltage());
              motor_id_15Sim.setSupplyVoltage(RobotController.getBatteryVoltage());

              /* Then calculate the new position and velocity of the simulated climber */
              climberSim_motor_id_15.setInputVoltage(motor_id_15Sim.getMotorVoltage());
              climberSim_motor_id_15.update(deltaTime);

              /* Apply the new rotor position and velocity to the motors (before gear ratio) */
              motor_id_19Sim.setRawRotorPosition(
                  Radians.of(
                      climberSim_motor_id_15.getPositionMeters()
                          / kDrumRadius.in(Meters)
                          * kGearRatio));
              motor_id_19Sim.setRotorVelocity(
                  RadiansPerSecond.of(
                      climberSim_motor_id_15.getVelocityMetersPerSecond()
                          / kDrumRadius.in(Meters)
                          * kGearRatio));
              motor_id_15Sim.setRawRotorPosition(
                  Radians.of(
                      climberSim_motor_id_15.getPositionMeters()
                          / kDrumRadius.in(Meters)
                          * kGearRatio));
              motor_id_15Sim.setRotorVelocity(
                  RadiansPerSecond.of(
                      climberSim_motor_id_15.getVelocityMetersPerSecond()
                          / kDrumRadius.in(Meters)
                          * kGearRatio));
            });
    simNotifier.startPeriodic(kSimLoopPeriod);
  }
}
