/* Generated by Phoenix Tuner X */
package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;
import static frc.robot.util.PhoenixUtil.applyConfig;

import com.ctre.phoenix6.BaseStatusSignal;
import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.StatusSignal;
import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.controls.DutyCycleOut;
import com.ctre.phoenix6.controls.MotionMagicVoltage;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.signals.GravityTypeValue;
import com.ctre.phoenix6.signals.NeutralModeValue;
import com.ctre.phoenix6.sim.ChassisReference;
import edu.wpi.first.epilogue.Logged;
import edu.wpi.first.epilogue.Logged.Importance;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.units.measure.*;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.simulation.DCMotorSim;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.button.Trigger;
import frc.robot.CAN;
import frc.robot.Mechanism;
import frc.robot.Robot;
import frc.robot.test.SelfTestable;
import java.util.function.DoubleSupplier;
import java.util.function.Supplier;
import lombok.Getter;

public class Climber extends Mechanism implements SelfTestable {
  /** Position setpoints for the climber. */
  public enum Setpoint {
    Bottom(Rotations.of(1)),
    Middle(Inches.of(3.5)),
    Top(Inches.of(6.5));

    /** The position target of the setpoint in angular units. */
    public final Angle target;

    /** The position target of the setpoint in linear units. */
    public final Distance targetDist;

    private Setpoint(Angle target) {
      this.target = target;
      this.targetDist = kDrumRadius.times(target.in(Radians));
    }

    private Setpoint(Distance target) {
      this.target = Radians.of(target.div(kDrumRadius).magnitude());
      this.targetDist = target;
    }
  }

  @Logged @Getter public boolean zeroed = false;

  private static final int SENSOR_PORT = 0;

  @Logged(name = "sensor", importance = Importance.CRITICAL)
  private final DigitalInput sensor = new DigitalInput(SENSOR_PORT);

  private static final double kGearRatio = 73.8;
  private static final Distance kDrumRadius = Meters.of(0.009525);

  private final CANBus kCANBus = new CANBus(CAN.NAME);
  private final TalonFX motor = new TalonFX(CAN.CLIMBER, kCANBus);

  /* device status signals */
  private final StatusSignal<Angle> motorPosition = motor.getPosition(false);
  private final StatusSignal<Current> motorTorqueCurrent = motor.getTorqueCurrent(false);

  private final StatusSignal<Current> motorSupplyCurrent = motor.getSupplyCurrent(false);
  private final StatusSignal<Current> motorStatorCurrent = motor.getStatorCurrent(false);
  private final StatusSignal<AngularVelocity> motorVelocity = motor.getVelocity(false);
  private final StatusSignal<Temperature> motorTemperature = motor.getDeviceTemp(false);
  private final StatusSignal<Double> motorClosedLoopError = motor.getClosedLoopError(false);

  // supplyCurrent ≈ statorCurrent × (motorVoltage / supplyVoltage)

  /* controls used by the motors */
  private final MotionMagicVoltage setpointRequest = new MotionMagicVoltage(0);
  private final DutyCycleOut manualRequest = new DutyCycleOut(0);
  private final DutyCycleOut calibrationRequest =
      new DutyCycleOut(-0.1).withIgnoreHardwareLimits(true).withIgnoreSoftwareLimits(true);

  /** Trigger to detect when the climber drives into a hard stop. */
  public final Trigger isHardStop =
      new Trigger(
              () -> {
                return motorVelocity.getValue().abs(RotationsPerSecond) < 1
                    && motorTorqueCurrent.getValue().abs(Amps)
                        > 10; // consider changing to statorcurrent for reliability
              })
          .debounce(0.1);

  /** Configs common across all motors. */
  private static final TalonFXConfiguration motorInitialConfigs = new TalonFXConfiguration();

  private final TalonFXConfiguration motorConfigs =
      motorInitialConfigs
          .clone()
          .withMotorOutput(
              motorInitialConfigs.MotorOutput.clone().withNeutralMode(NeutralModeValue.Brake))
          .withCurrentLimits(
              motorInitialConfigs
                  .CurrentLimits
                  .clone()
                  .withStatorCurrentLimit(Amps.of(120))
                  .withStatorCurrentLimitEnable(true))
          .withSlot0(
              motorInitialConfigs
                  .Slot0
                  .clone()
                  .withKP(33.0)
                  .withKI(0)
                  .withKD(0)
                  .withKS(0.2)
                  .withKV(8.856)
                  .withKA(0)
                  .withKG(0)
                  .withGravityType(GravityTypeValue.Elevator_Static))
          .withFeedback(motorInitialConfigs.Feedback.clone().withSensorToMechanismRatio(kGearRatio))
          .withSoftwareLimitSwitch(
              motorInitialConfigs
                  .SoftwareLimitSwitch
                  .clone()
                  .withForwardSoftLimitThreshold(Setpoint.Top.target.in(Rotations))
                  .withForwardSoftLimitEnable(true)
                  .withReverseSoftLimitThreshold(0.0)
                  .withReverseSoftLimitEnable(true))
          .withMotionMagic(
              motorInitialConfigs
                  .MotionMagic
                  .clone()
                  .withMotionMagicCruiseVelocity(RotationsPerSecond.of(1.2))
                  .withMotionMagicAcceleration(RotationsPerSecondPerSecond.of(5.0)));

  private DCMotorSim motorSimModel;

  public Climber() {
    super("Climber");
    applyConfig(() -> motor.getConfigurator().apply(motorConfigs), getName());

    optimizeCAN();

    if (Robot.isSimulation()) {
      motorSimModel =
          simulationInitKrakenX60(
              motor, kGearRatio, 0.01, ChassisReference.CounterClockwise_Positive);
    }
    System.out.println(getName() + " Subsystem Initialized");
  }

  private void optimizeCAN() {
    motorPosition.setUpdateFrequency(250);
    motorTorqueCurrent.setUpdateFrequency(50);
    motorSupplyCurrent.setUpdateFrequency(50);
    motorStatorCurrent.setUpdateFrequency(50);
    motorVelocity.setUpdateFrequency(250);
    motorTemperature.setUpdateFrequency(10);
    motorClosedLoopError.setUpdateFrequency(50);

    motor.optimizeBusUtilization();
  }

  /**
   * @return true if the tower rung is blocking the climber sensor.
   */
  @Logged(name = "climberBlocked", importance = Importance.CRITICAL)
  public boolean climberBlocked() {
    return !sensor.get();
  }

  public boolean isAtTop() {
    return Math.abs(getPositionInches() - Setpoint.Top.targetDist.in(Inches)) < .5;
  }

  public boolean isAtBottom() {
    return Math.abs(getPositionInches() - Setpoint.Bottom.targetDist.in(Inches)) < .5;
  }

  /**
   * @return The Position of the climber
   */
  @Logged(name = "position")
  public Angle getPosition() {
    return motorPosition.getValue();
  }

  @Logged(name = "positionDistance")
  public Distance getPositionDistance() {
    return kDrumRadius.times(motorPosition.getValue().in(Radians));
  }

  @Logged(name = "positionInches")
  public double getPositionInches() {
    return kDrumRadius.times(motorPosition.getValue().in(Radians)).in(Inches);
  }

  /**
   * @return The TorqueCurrent of the climber
   */
  @Logged
  public Current getTorqueCurrent() {
    return motorTorqueCurrent.getValue();
  }

  @Logged(name = "closedLoopError")
  public double getClosedLoopError() {
    return motorClosedLoopError.getValue();
  }

  @Logged(name = "velocity")
  public AngularVelocity getVelocity() {
    return motorVelocity.getValue();
  }

  @Logged(name = "supplyCurrent")
  public Current getSupplyCurrent() {
    return motorSupplyCurrent.getValue();
  }

  @Logged(name = "statorCurrent")
  public Current getStatorCurrent() {
    return motorStatorCurrent.getValue();
  }

  @Logged(name = "temperature")
  public double getTemperature() {
    return motorTemperature.getValue().in(Celsius);
  }

  /**
   * Holds the climber at the current position using PID.
   *
   * @return Command to run
   */
  public Command holdPosition() {
    return runOnce(() -> setpointRequest.withPosition(motorPosition.getValue()))
        .andThen(
            run(
                () -> {
                  motor.setControl(setpointRequest);
                }));
  }

  public Command raise() {
    return goToSetpoint(() -> Climber.Setpoint.Top);
  }

  public Command lower() {
    return goToSetpoint(() -> Climber.Setpoint.Bottom);
  }

  /**
   * Drives the climber to the provided position setpoint.
   *
   * @param setpoint Function returning the setpoint to apply
   * @return Command to run
   */
  public Command goToSetpoint(Supplier<Setpoint> setpoint) {
    return run(
        () -> {
          setpointRequest.withPosition(setpoint.get().target);
          motor.setControl(setpointRequest);
        });
  }

  /**
   * Manually drives the climber with the provided duty cycle output.
   *
   * @param manualOutput Function returning the duty cycle to apply
   * @return Command to run
   */
  public Command manualDrive(DoubleSupplier manualOutput) {
    return run(
        () -> {
          manualRequest.withOutput(manualOutput.getAsDouble());
          motor.setControl(manualRequest);
        });
  }

  @Logged private boolean selfTestPassed = false;
  private static final double SELF_TEST_TOLERANCE_INCHES = 0.5;

  // TODO: safeguard the position of the climber, should start at 0
  // TODO: retract climber at end of test
  private Command selfTestAt(Setpoint target, String ntKey) {
    return Commands.runOnce(
            () -> {
              var nt = NetworkTableInstance.getDefault();
              nt.getEntry(ntKey + "/message").setString("Running...");
              nt.getEntry(ntKey + "/passed").unpublish();
              ;
            })
        .andThen(calibrateZero())
        .andThen(goToSetpoint(() -> target))
        .withName(getName() + ".TestSetpoint" + target.name())
        .withTimeout(3.0)
        .andThen(
            runOnce(
                () -> {
                  double errorInches = Math.abs(getPositionInches() - target.targetDist.in(Inches));
                  selfTestPassed = errorInches < SELF_TEST_TOLERANCE_INCHES;
                  String result =
                      (selfTestPassed ? "PASS" : "FAIL")
                          + ": "
                          + String.format("%.2f", getPositionInches())
                          + "\" (target "
                          + target.targetDist.in(Inches)
                          + ")";
                  var nt = NetworkTableInstance.getDefault();
                  nt.getEntry(ntKey + "/passed").setBoolean(selfTestPassed);
                  nt.getEntry(ntKey + "/message").setString(result);
                }))
        .andThen(lower().withTimeout(3.0))
        .finallyDo(() -> motor.stopMotor());
  }

  @Override
  public Command selfTestSlow() {
    return selfTestAt(Setpoint.Middle, "Robot/Tests/climber/slow")
        .withName(getName() + ".SelfTestSlow");
  }

  @Override
  public Command selfTestFast() {
    return selfTestAt(Setpoint.Top, "Robot/Tests/climber/fast")
        .withName(getName() + ".SelfTestFast");
  }

  /**
   * Recalibrates the climber zero point. This slowly drives the climber down until we see a drop in
   * velocity and a spike in stator current, indicating that we've hit a hard stop.
   *
   * @return Command to run
   */
  public Command calibrateZero() {
    return run(() -> {
          motor.setControl(calibrationRequest);
        })
        .until(isHardStop)
        .andThen(
            manualDrive(() -> 0.0)
                .withTimeout(0.25)
                .finallyDo(
                    () -> {
                      motor.setPosition(Rotations.of(0));
                      zeroed = true;
                    }))
        .withName("CalibrateClimber");
  }

  @Override
  public void periodic() {
    /* refresh all status signals */
    BaseStatusSignal.refreshAll(
        motorPosition,
        motorVelocity,
        motorTorqueCurrent,
        motorTemperature,
        motorSupplyCurrent,
        motorStatorCurrent,
        motorClosedLoopError);
  }

  @Override
  public void simulationPeriodic() {
    super.simulationPeriodic(motor, kGearRatio, motorSimModel);
  }
}
