/* Generated by Phoenix Tuner X */
package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import com.ctre.phoenix6.BaseStatusSignal;
import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.StatusCode;
import com.ctre.phoenix6.StatusSignal;
import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.controls.DutyCycleOut;
import com.ctre.phoenix6.controls.Follower;
import com.ctre.phoenix6.controls.MotionMagicVoltage;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.signals.GravityTypeValue;
import com.ctre.phoenix6.signals.MotorAlignmentValue;
import com.ctre.phoenix6.signals.NeutralModeValue;
import edu.wpi.first.epilogue.Logged;
import edu.wpi.first.epilogue.Logged.Importance;
import edu.wpi.first.units.measure.*;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import edu.wpi.first.wpilibj2.command.button.Trigger;
import java.util.function.DoubleSupplier;
import java.util.function.Supplier;

public class Climber extends SubsystemBase {
  /** Position setpoints for the climber. */
  public enum Setpoint {
    Bottom(Rotations.of(0)),
    Middle(Inches.of(3.5)),
    Top(Inches.of(6.75)); // 16.5 rotations

    /** The position target of the setpoint in angular units. */
    public final Angle target;

    /** The position target of the setpoint in linear units. */
    public final Distance targetDist;

    private Setpoint(Angle target) {
      this.target = target;
      this.targetDist = kDrumRadius.times(target.in(Radians));
    }

    private Setpoint(Distance target) {
      this.target = Radians.of(target.div(kDrumRadius).magnitude());
      this.targetDist = target;
    }
  }

  private static final int SENSOR_PORT = 0;

  @Logged(name = "Climber Sensor", importance = Importance.CRITICAL)
  private final DigitalInput sensor = new DigitalInput(SENSOR_PORT);

  private static final int kNumConfigAttempts = 2;

  private static final double kGearRatio = 24.6;
  private static final Distance kDrumRadius = Meters.of(0.009525);

  /* leader and follower motors */
  private final CANBus kCANBus = new CANBus("Default Name");
  private final TalonFX follower = new TalonFX(19, kCANBus); // follower
  private final TalonFX leader = new TalonFX(15, kCANBus); // leader

  /* device status signals */
  private final StatusSignal<Angle> leaderPosition = leader.getPosition(false);
  private final StatusSignal<AngularVelocity> leaderVelocity = leader.getVelocity(false);
  private final StatusSignal<Current> leaderTorqueCurrent = leader.getTorqueCurrent(false);
  private final StatusSignal<Temperature> leaderTemperature = leader.getDeviceTemp(false);
  private final StatusSignal<Current> followerTorqueCurrent = follower.getTorqueCurrent(false);
  private final StatusSignal<Temperature> followerTemperature = follower.getDeviceTemp(false);

  /* controls used by the leader motors */
  private final MotionMagicVoltage setpointRequest = new MotionMagicVoltage(0);
  private final DutyCycleOut manualRequest = new DutyCycleOut(0);
  private final DutyCycleOut calibrationRequest =
      new DutyCycleOut(-0.1).withIgnoreHardwareLimits(true).withIgnoreSoftwareLimits(true);

  /** Trigger to detect when the climber drives into a hard stop. */
  public final Trigger isHardStop =
      new Trigger(
              () -> {
                return leaderVelocity.getValue().abs(RotationsPerSecond) < 1
                    && leaderTorqueCurrent.getValue().abs(Amps)
                        > 10; // consider changing to statorcurrent for reliability
              })
          .debounce(0.1);

  /** Configs common across all motors. */
  private static final TalonFXConfiguration motorInitialConfigs = new TalonFXConfiguration();

  /** Configs common across just the leader motors. */
  private static final TalonFXConfiguration leaderInitialConfigs = motorInitialConfigs.clone();

  /** Configs for {@link #follower}. */
  private final TalonFXConfiguration followerConfigs =
      motorInitialConfigs
          .clone()
          .withMotorOutput(
              motorInitialConfigs.MotorOutput.clone().withNeutralMode(NeutralModeValue.Brake))
          .withCurrentLimits(
              motorInitialConfigs
                  .CurrentLimits
                  .clone()
                  .withStatorCurrentLimit(Amps.of(120))
                  .withStatorCurrentLimitEnable(true));

  /** Configs for {@link #leader}. */
  private final TalonFXConfiguration leaderConfigs =
      leaderInitialConfigs
          .clone()
          .withMotorOutput(
              leaderInitialConfigs.MotorOutput.clone().withNeutralMode(NeutralModeValue.Brake))
          .withCurrentLimits(
              leaderInitialConfigs
                  .CurrentLimits
                  .clone()
                  .withStatorCurrentLimit(Amps.of(120))
                  .withStatorCurrentLimitEnable(true))
          .withSlot0(
              leaderInitialConfigs
                  .Slot0
                  .clone()
                  .withKP(98.4)
                  .withKI(0)
                  .withKD(0)
                  .withKS(0.2)
                  .withKV(2.952)
                  .withKA(0)
                  .withKG(0)
                  .withGravityType(GravityTypeValue.Elevator_Static))
          .withFeedback(
              leaderInitialConfigs.Feedback.clone().withSensorToMechanismRatio(kGearRatio))
          .withSoftwareLimitSwitch(
              motorInitialConfigs
                  .SoftwareLimitSwitch
                  .clone()
                  .withForwardSoftLimitThreshold(Setpoint.Top.target.in(Rotations))
                  .withForwardSoftLimitEnable(true)
                  .withReverseSoftLimitThreshold(0.0)
                  .withReverseSoftLimitEnable(true))
          .withMotionMagic(
              leaderInitialConfigs
                  .MotionMagic
                  .clone()
                  .withMotionMagicCruiseVelocity(RotationsPerSecond.of(3.252032520325203))
                  .withMotionMagicAcceleration(RotationsPerSecondPerSecond.of(16.260162601626014)));

  public Climber() {
    super("Climber");
    StatusCode status = follower.getConfigurator().apply(followerConfigs);

    for (int i = 0; i < kNumConfigAttempts; ++i) {
      if (status.isOK()) break;
      status = follower.getConfigurator().apply(followerConfigs);
    }
    if (!status.isOK()) {
      System.out.println("ERROR Configuring Climber follower motor: " + status);
    }

    status = leader.getConfigurator().apply(leaderConfigs);
    for (int i = 0; i < kNumConfigAttempts; ++i) {
      if (status.isOK()) break;
      status = leader.getConfigurator().apply(leaderConfigs);
    }
    if (!status.isOK()) {
      System.out.println("ERROR Configuring Climber leader motor: " + status);
    }

    follower.setControl(new Follower(leader.getDeviceID(), MotorAlignmentValue.Aligned));

    optimizeCAN();
    System.out.println("Climber Subsystem Initialized");
  }

  private void optimizeCAN() {
    leader.getPosition().setUpdateFrequency(100);
    leader.getVelocity().setUpdateFrequency(100);
    leader.getSupplyCurrent().setUpdateFrequency(50);
    leader.getDeviceTemp().setUpdateFrequency(4);

    leader.optimizeBusUtilization();

    follower.getSupplyCurrent().setUpdateFrequency(10);
    follower.getDeviceTemp().setUpdateFrequency(4);

    follower.optimizeBusUtilization();
  }

  /**
   * @return true if the tower rung is blocking the climber sensor.
   */
  @Logged(name = "Climber Blocked", importance = Importance.CRITICAL)
  public boolean climberBlocked() {
    return !sensor.get();
  }

  /**
   * @return The Position of the climber
   */
  @Logged
  public Angle getPosition() {
    return leaderPosition.getValue();
  }

  @Logged
  public Distance getPositionDistance() {
    return kDrumRadius.times(leaderPosition.getValue().in(Radians));
  }

  @Logged
  public double getPositionInches() {
    return kDrumRadius.times(leaderPosition.getValue().in(Radians)).in(Inches);
  }

  /**
   * @return The Velocity of the climber
   */
  @Logged
  public AngularVelocity getVelocity() {
    return leaderVelocity.getValue();
  }

  /**
   * @return The TorqueCurrent of the climber
   */
  @Logged
  public Current getTorqueCurrentA() {
    return leaderTorqueCurrent.getValue();
  }

  /**
   * @return The TorqueCurrent of the climber
   */
  @Logged
  public Current getTorqueCurrentB() {
    return followerTorqueCurrent.getValue();
  }

  /**
   * @return The Temperature of the climber
   */
  @Logged
  public double getTemperatureAFahrenheit() {
    return leaderTemperature.getValue().in(Fahrenheit);
  }

  /**
   * @return The Temperature of the climber
   */
  @Logged
  public double getTemperatureBFahrenheit() {
    return followerTemperature.getValue().in(Fahrenheit);
  }

  /**
   * Holds the climber at the current position using PID.
   *
   * @return Command to run
   */
  public Command holdPosition() {
    return runOnce(() -> setpointRequest.withPosition(leaderPosition.getValue()))
        .andThen(
            run(
                () -> {
                  leader.setControl(setpointRequest);
                }));
  }

  public Command raise() {
    return goToSetpoint(() -> Climber.Setpoint.Top);
  }

  public Command lower() {
    return goToSetpoint(() -> Climber.Setpoint.Bottom);
  }

  /**
   * Drives the climber to the provided position setpoint.
   *
   * @param setpoint Function returning the setpoint to apply
   * @return Command to run
   */
  public Command goToSetpoint(Supplier<Setpoint> setpoint) {
    return run(
        () -> {
          setpointRequest.withPosition(setpoint.get().target);
          leader.setControl(setpointRequest);
        });
  }

  /**
   * Manually drives the climber with the provided duty cycle output.
   *
   * @param manualOutput Function returning the duty cycle to apply
   * @return Command to run
   */
  public Command manualDrive(DoubleSupplier manualOutput) {
    return run(
        () -> {
          manualRequest.withOutput(manualOutput.getAsDouble());
          leader.setControl(manualRequest);
        });
  }

  /**
   * Recalibrates the climber zero point. This slowly drives the climber down until we see a drop in
   * velocity and a spike in stator current, indicating that we've hit a hard stop.
   *
   * @return Command to run
   */
  public Command calibrateZero() {
    return run(() -> {
          leader.setControl(calibrationRequest);
        })
        .until(isHardStop)
        .andThen(
            manualDrive(() -> 0.0)
                .withTimeout(0.25)
                .finallyDo(
                    () -> {
                      leader.setPosition(Rotations.of(0));
                    }));
  }

  @Override
  public void periodic() {
    /* refresh all status signals */
    BaseStatusSignal.refreshAll(
        leaderPosition,
        leaderVelocity,
        leaderTorqueCurrent,
        leaderTemperature,
        followerTorqueCurrent,
        followerTemperature);
  }
}
