/* Generated by Phoenix Tuner X */
package frc.robot.subsystems.shooter;

import static edu.wpi.first.units.Units.*;

import com.ctre.phoenix6.BaseStatusSignal;
import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.StatusCode;
import com.ctre.phoenix6.StatusSignal;
import com.ctre.phoenix6.configs.SoftwareLimitSwitchConfigs;
import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.controls.DutyCycleOut;
import com.ctre.phoenix6.controls.MotionMagicVoltage;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.signals.GravityTypeValue;
import com.ctre.phoenix6.signals.NeutralModeValue;
import edu.wpi.first.epilogue.Logged;
import edu.wpi.first.math.system.plant.DCMotor;
import edu.wpi.first.units.measure.*;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.simulation.ElevatorSim;
import edu.wpi.first.wpilibj.smartdashboard.Mechanism2d;
import edu.wpi.first.wpilibj.smartdashboard.MechanismLigament2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import edu.wpi.first.wpilibj2.command.button.Trigger;
import java.util.function.DoubleSupplier;
import java.util.function.Supplier;

public class Hood extends SubsystemBase {
  /** Position setpoints for the hood. */
  public enum Setpoint {
    Ground(Rotations.of(0)),
    Middle(Rotations.of(0.7)),
    Top(Rotations.of(1.3));

    /** The position target of the setpoint in angular units. */
    public final Angle target;

    /** The position target of the setpoint in linear units. */
    public final Distance targetDist;

    private Setpoint(Angle target) {
      this.target = target;
      this.targetDist = kDrumRadius.times(target.in(Radians));
    }

    private Setpoint(Distance target) {
      this.target = Radians.of(target.div(kDrumRadius).magnitude());
      this.targetDist = target;
    }
  }

  private static final int kNumConfigAttempts = 2;

  private static final double kGearRatio = 1.2;
  private static final Distance kDrumRadius = Meters.of(0.028575);
  private static final Distance kMaxHeight = Meters.of(0);
  private final Angle MIN_ANGLE = Degrees.of(32);
  private final Angle MAX_ANGLE = Degrees.of(69.5);

  /* leader and follower motors */
  private final CANBus kCANBus = new CANBus("Default Name");
  private final TalonFX motor = new TalonFX(25, kCANBus);

  /* device status signals */
  private final StatusSignal<Angle> motorPosition = motor.getPosition(false);
  private final StatusSignal<AngularVelocity> motorVelocity = motor.getVelocity(false);
  private final StatusSignal<Current> motorTorqueCurrent = motor.getTorqueCurrent(false);

  /* controls used by the leader motors */
  private final MotionMagicVoltage setpointRequest = new MotionMagicVoltage(0);
  private final DutyCycleOut manualRequest = new DutyCycleOut(0);
  private final DutyCycleOut calibrationRequest =
      new DutyCycleOut(-0.1).withIgnoreHardwareLimits(true).withIgnoreSoftwareLimits(true);

  /** Trigger to detect when the hood drives into a hard stop. */
  public final Trigger isHardStop =
      new Trigger(
              () -> {
                return motorVelocity.getValue().abs(RotationsPerSecond) < 1
                    && motorTorqueCurrent.getValue().abs(Amps) > 10;
              })
          .debounce(0.1);

  /* simulation */
  private final ElevatorSim hoodSim_motor =
      new ElevatorSim(
          DCMotor.getKrakenX60Foc(1),
          kGearRatio,
          5,
          kDrumRadius.in(Meters),
          0.0,
          kMaxHeight.in(Meters),
          true,
          0.0);

  private static final double kSimLoopPeriod = 0.002; // 2 ms
  private Notifier simNotifier = null;
  private double lastSimTime = 0.0;

  /* Mechanism2d visualization of the hood */
  private final Mechanism2d mech2d = new Mechanism2d(1, kMaxHeight.in(Meters));
  private final MechanismLigament2d motorMech2d =
      mech2d
          .getRoot("motor Root", 0.500, 0)
          .append(new MechanismLigament2d("motor", hoodSim_motor.getPositionMeters(), 90));

  /** Configs common across all motors. */
  private static final TalonFXConfiguration motorInitialConfigs = new TalonFXConfiguration();

  /** Configs common across just the leader motors. */
  private static final TalonFXConfiguration leaderInitialConfigs = motorInitialConfigs.clone();

  /** Configs for {@link #motor}. */
  private final TalonFXConfiguration motorConfigs =
      leaderInitialConfigs
          .clone()
          .withMotorOutput(
              leaderInitialConfigs.MotorOutput.clone().withNeutralMode(NeutralModeValue.Brake))
          .withCurrentLimits(
              leaderInitialConfigs
                  .CurrentLimits
                  .clone()
                  .withStatorCurrentLimit(Amps.of(120))
                  .withStatorCurrentLimitEnable(true))
          .withSlot0(
              leaderInitialConfigs
                  .Slot0
                  .clone()
                  .withKP(2.4)
                  .withKI(0)
                  .withKD(0)
                  .withKS(0.2)
                  .withKV(0.0)
                  .withKA(0)
                  .withKG(0.28)
                  .withGravityType(GravityTypeValue.Elevator_Static))
          .withFeedback(leaderInitialConfigs.Feedback.clone().withSensorToMechanismRatio(1.2))
          .withSoftwareLimitSwitch(
              new SoftwareLimitSwitchConfigs()
                  .withForwardSoftLimitThreshold(1.4)
                  .withForwardSoftLimitEnable(true)
                  .withReverseSoftLimitThreshold(0.0)
                  .withReverseSoftLimitEnable(true))
          .withMotionMagic(
              leaderInitialConfigs
                  .MotionMagic
                  .clone()
                  .withMotionMagicCruiseVelocity(RotationsPerSecond.of(66))
                  .withMotionMagicAcceleration(RotationsPerSecondPerSecond.of(300)));

  public Hood() {
    super("Hood");
    StatusCode status = motor.getConfigurator().apply(motorConfigs);

    for (int i = 0; i < kNumConfigAttempts; ++i) {
      if (status.isOK()) break;

      status = motor.getConfigurator().apply(motorConfigs);
    }
    if (!status.isOK()) {
      System.out.println("ERROR Configuring Hood motor: " + status);
    }

    SmartDashboard.putData("Hood", mech2d);

    motor.setPosition(Rotations.of(0.0));
    optimizeCAN();
    System.out.println("Hood Subsystem Initialized");
  }

  private void optimizeCAN() {
    motor.getPosition().setUpdateFrequency(100);
    motor.getVelocity().setUpdateFrequency(100);
    motor.getSupplyCurrent().setUpdateFrequency(50);
    motor.getDeviceTemp().setUpdateFrequency(4);

    motor.optimizeBusUtilization();
  }

  /**
   * @return The Position of the hood
   */
  @Logged
  public Angle getHoodPosition() {
    return motorPosition.getValue();
  }

  @Logged
  public double getRotations() {
    return motorPosition.getValue().in(Rotations);
  }

  /**
   * @return The Velocity of the hood
   */
  public AngularVelocity getVelocity() {
    return motorVelocity.getValue();
  }

  /**
   * @return The TorqueCurrent of the hood
   */
  public Current getTorqueCurrent() {
    return motorTorqueCurrent.getValue();
  }

  @Logged
  public Angle getSetpoint() {
    return setpointRequest.getPositionMeasure();
  }

  @Logged
  public boolean isAtSetpoint() {
    return getHoodPosition().isNear(getSetpoint(), 0.05);
  }

  /**
   * Holds the hood at the current position using PID.
   *
   * @return Command to run
   */
  public Command holdPosition() {
    return runOnce(() -> setpointRequest.withPosition(motorPosition.getValue()))
        .andThen(
            run(
                () -> {
                  motor.setControl(setpointRequest);
                }));
  }

  /**
   * Drives the hood to the provided position setpoint.
   *
   * @param setpoint Function returning the setpoint to apply
   * @return Command to run
   */
  public Command goToSetpoint(Supplier<Setpoint> setpoint) {
    return run(
        () -> {
          setpointRequest.withPosition(setpoint.get().target);
          motor.setControl(setpointRequest);
        });
  }

  public Command goToSetpointAngle(Supplier<Angle> value) {
    return run(
        () -> {
          setpointRequest.withPosition(value.get());
          motor.setControl(setpointRequest);
        });
  }

  public Command goToSetpointRotationsDouble(DoubleSupplier value) {
    return run(
        () -> {
          setpointRequest.withPosition(Rotations.of(value.getAsDouble()));
          motor.setControl(setpointRequest);
        });
  }

  @Override
  public void periodic() {
    /* refresh all status signals */
    BaseStatusSignal.refreshAll(motorPosition, motorVelocity, motorTorqueCurrent);
  }
}
