package frc.robot.state;

import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.button.CommandXboxController;
import edu.wpi.first.wpilibj2.command.button.Trigger;
import frc.robot.commands.DynamicShootingCommand;
import frc.robot.subsystems.Intake;
import frc.robot.subsystems.IntakeArm;
import frc.robot.subsystems.shooter.Flywheel;

/**
 * Wires up the {@link GameStateStateMachine} transitions to driver inputs and sensor conditions.
 *
 * <p>Instantiate once in {@code Robot}, then call {@link #poll()} before {@code
 * CommandScheduler.getInstance().run()} in {@code robotPeriodic()} so that state transitions are
 * resolved before commands execute on that loop cycle.
 *
 * <h2>Intake flow</h2>
 *
 * <pre>
 *   IDLE ──(left trigger pressed)──▶ INTAKING
 *   INTAKING ──(left trigger released)──▶ IDLE
 * </pre>
 *
 * <h2>Shooter flow</h2>
 *
 * <pre>
 *   IDLE ──(right trigger pressed)──▶ SPINNING_UP
 *   SPINNING_UP ──(flywheel @ target)──▶ SHOOTING
 *   SPINNING_UP ──(right trigger released)──▶ IDLE  (cancel before up to speed)
 *   SHOOTING ──(right trigger released)──▶ IDLE
 * </pre>
 */
public class GameStateMachineSetup {

  // Generated by the FoxFlow annotation processor from GameState.java
  private final GameStateStateMachine stateMachine;

  public GameStateMachineSetup(
      CommandXboxController pilot,
      Intake intake,
      IntakeArm intakeArm,
      Flywheel flywheel,
      DynamicShootingCommand shootingCommand) {

    stateMachine = new GameStateStateMachine(IntakeState.IDLE, ShooterState.IDLE);

    configureIntakeTransitions(pilot, intake, intakeArm);
    configureShooterTransitions(pilot, flywheel, shootingCommand);
  }

  // ── Intake ─────────────────────────────────────────────────────────────────

  private void configureIntakeTransitions(
      CommandXboxController pilot, Intake intake, IntakeArm intakeArm) {

    // IDLE → INTAKING: extend arm then start roller when driver pulls left trigger
    stateMachine
        .state(IntakeState.IDLE)
        .to(IntakeState.INTAKING)
        .transitionWhen(pilot.leftTrigger())
        .run(intake.runRoller().andThen(intakeArm.extend()));

    // INTAKING → IDLE: retract arm and stop roller (after 1 s delay) on trigger release
    stateMachine
        .state(IntakeState.INTAKING)
        .to(IntakeState.IDLE)
        .transitionWhen(pilot.leftTrigger().negate())
        .run(
            intakeArm
                .retract()
                .alongWith(Commands.waitSeconds(1).andThen(intake.stopRollerCommand())));
  }

  // ── Shooter ────────────────────────────────────────────────────────────────

  private void configureShooterTransitions(
      CommandXboxController pilot, Flywheel flywheel, DynamicShootingCommand shootingCommand) {

    // IDLE → SPINNING_UP: start flywheel + hood spin-up when driver pulls right trigger.
    // shootingCommand.shoot() spins up the flywheel, positions the hood, and feeds the note once
    // the flywheel is at speed — all as a single background command.
    stateMachine
        .state(ShooterState.IDLE)
        .to(ShooterState.SPINNING_UP)
        .transitionWhen(pilot.rightTrigger())
        .run(shootingCommand.shoot());

    // SPINNING_UP → SHOOTING: advance state once the flywheel hits target velocity.
    // No command here — the shoot() command already handles the spindexer internally.
    stateMachine
        .state(ShooterState.SPINNING_UP)
        .to(ShooterState.SHOOTING)
        .transitionWhen(flywheel::isAtTarget);

    // SPINNING_UP → IDLE (cancel): driver releases trigger before reaching speed
    stateMachine
        .state(ShooterState.SPINNING_UP)
        .to(ShooterState.IDLE)
        .transitionWhen(pilot.rightTrigger().negate())
        .run(shootingCommand.stop());

    // SHOOTING → IDLE: driver releases trigger after firing
    stateMachine
        .state(ShooterState.SHOOTING)
        .to(ShooterState.IDLE)
        .transitionWhen(pilot.rightTrigger().negate())
        .run(shootingCommand.stop());
  }

  // ── Public API ─────────────────────────────────────────────────────────────

  /**
   * Evaluates all registered transition conditions and fires any that are satisfied.
   *
   * <p>Call this <em>before</em> {@code CommandScheduler.getInstance().run()} in {@code
   * robotPeriodic()} so that commands scheduled by transitions run on the same loop cycle.
   */
  public void poll() {
    stateMachine.poll();
  }

  /**
   * Returns a trigger that is active while the robot is in the given intake state.
   *
   * <p>Useful for LED control and driver feedback:
   *
   * <pre>{@code
   * intakeStateTrigger(IntakeState.INTAKING)
   *     .onTrue(Commands.runOnce(() -> leds.setColor(Color.kGreen)))
   *     .onFalse(Commands.runOnce(() -> leds.setColor(Color.kBlack)));
   * }</pre>
   */
  public Trigger intakeStateTrigger(IntakeState state) {
    return stateMachine.state(state).trigger();
  }

  /**
   * Returns a trigger that is active while the robot is in the given shooter state.
   *
   * <p>Useful for driver feedback such as a "ready to shoot" indicator:
   *
   * <pre>{@code
   * shooterStateTrigger(ShooterState.SHOOTING)
   *     .onTrue(Commands.runOnce(() -> leds.setColor(Color.kRed)));
   * }</pre>
   */
  public Trigger shooterStateTrigger(ShooterState state) {
    return stateMachine.state(state).trigger();
  }

  /** Returns the underlying state machine for advanced use. */
  public GameStateStateMachine stateMachine() {
    return stateMachine;
  }
}
